source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNMediaUploadQueue_Example', :exclusive => true do
  pod "NNMediaUploadQueue", :path => "../"
end

target 'NNMediaUploadQueue_Tests', :exclusive => true do
  pod "NNMediaUploadQueue", :path => "../"

  
end
